// This file is the executable file for the setup command.
// DO NOT EDIT THIS FILE! 

import figlet from "figlet"
import admin from "firebase-admin"
import chalk from "chalk"
import fs from "fs"
import { type ServiceAccount } from "firebase-admin"
import { select, text, isCancel } from "@clack/prompts"
import secretFile from "../secret.json" with { type: "json" }

// Log func
function logInfo(message: string) {
  console.log(chalk.blue(`|  Info: ${message}`))
}

function logWarn(message: string) {
  console.log(chalk.yellow(`|  Warn: ${message}`))
}

function logComplete(message: string) {
  console.log(chalk.green(`|  Complete: ${message}`))
}

function logError(message: string) {
  console.log(chalk.red(`|  Error: ${message}`))
}

// Init app for product
const productApp = admin.initializeApp({ credential: admin.credential.cert(secretFile as ServiceAccount) })
const productDb = productApp.firestore()

// Init app for emulator
const emulatorApp = admin.initializeApp({ credential: admin.credential.cert(secretFile as ServiceAccount) }, "emulatorApp")
const emulatorDb = emulatorApp.firestore()

// Connect emulator & set confirm state
emulatorDb.settings({ host: "localhost:8080", ssl: false })
let isEmulator: boolean = true
let isNormalSetup: boolean = true

async function startup() {
  const choice = await select({
    message: "Would you like to set up the project?",
    options: [
      { value: "yes", label: "Yes" },
      { value: "no", label: "No" }
    ]
  })

  if (choice === "no") {
    logWarn("Setup is cancelled.")
    process.exit(0)
  } else {
    logComplete("Welcome to React Template Setup!")
  }
}

async function selectSetupTypes() {
  async function connectEmulator() {
    logInfo("Connecting firebase emulator...")

    // Set timeout 5 seconds
    const timeout = new Promise((_, reject) =>
      setTimeout(() => reject(new Error("timeout")), 5000)
    )

    try {
      await Promise.race([
        emulatorDb.collection("test").get(),
        timeout
      ])

      logInfo("Connected firebase emulator!")
    } catch {
      logError("Could not connect to emulator.")
      
      const choice = await select({
        message: "Do you want to connect again?",
        options: [
          { value: "yes", label: "Yes" },
          { value: "no", label: "No" }
        ]
      })

      if (choice === "no") {
        isEmulator = false
      } else {
        await connectEmulator()
      }
    }
  }

  const choice = await select({
    message: "Please select the setup type.",
    options: [
      { value: "normalSetup", label: "Normal setup mode" },
      { value: "onlyEmulator", label: "Only emulator" }
    ]
  })

  await connectEmulator()

  switch (choice) {
    case "normalSetup":
      break
    case "onlyEmulator":
      isNormalSetup = false
      break
  }
}

async function createEnv() {
  // Snnounce
  logInfo("Now, let's set up the .env and .firebaserc file! & .firebaserc!")
  logInfo("Please enter the following information.")

  const questions = [
    ["title", "Please enter your project title"],
    ["description", "Description"],
    ["firebase_api_key", "Firebase API Key"],
    ["firebase_auth_domain", "Firebase Auth Domain"],
    ["firebase_project_id", "Firebase Project ID"],
    ["firebase_storage_bucket", "Firebase Storage Bucket"],
    ["firebase_messaging_sender_id", "Firebase Messaging Sender ID"],
    ["firebase_app_id", "Firebase App ID"]
  ] as const

  // Get info
  const answers: Record<string, string | symbol> = {}
  for (const [key, message] of questions) {
    answers[key] = await text({ message })
  }

  // Confirm cancel
  if (Object.values(answers).some(isCancel)) {
    logWarn("You canceled")
    process.exit(0)
  }

  // Set value
  const {
    title,
    description,
    firebase_api_key,
    firebase_auth_domain,
    firebase_project_id,
    firebase_storage_bucket,
    firebase_messaging_sender_id,
    firebase_app_id
  } = answers as Record<string, string>
  
  // Create env
  const envContents = `VITE_TITLE=${title}\nVITE_FIREBASE_API_KEY=${firebase_api_key}\nVITE_FIREBASE_AUTH_DOMAIN=${firebase_auth_domain}\nVITE_FIREBASE_PROJECT_ID=${firebase_project_id}\nVITE_FIREBASE_STORAGE_BUCKET=${firebase_storage_bucket}\nVITE_FIREBASE_MESSAGING_SENDER_ID=${firebase_messaging_sender_id}\nVITE_FIREBASE_APP_ID=${firebase_app_id}`
  fs.writeFileSync(".env", envContents)

  // Update translate file
  const translatePath = "./src/translate/en.json"
  const translateFile = JSON.parse(fs.readFileSync(translatePath, "utf8"))
  translateFile.title.introduce = description
  fs.writeFileSync(translatePath, JSON.stringify(translateFile, null, 2))

  // Update japanese files too
  const translateJaPath = "./src/translate/en.json"
  const translateJaFile = JSON.parse(fs.readFileSync(translatePath, "utf8"))
  translateJaFile.title.introduce = description
  fs.writeFileSync(translatePath, JSON.stringify(translateJaFile, null, 2))

  // Creating .firebaserc from firebase_project_id
  fs.writeFileSync(".firebaserc", JSON.stringify({
    projects: {
      default: firebase_project_id
    }
  }, null, 2))

  logComplete(".env and .firebaserc file has been created successfully!")
}

async function createFirestore() {
  // Announce
  logInfo("Now, let's create first firestore data!")
  logInfo("Please enter the following information.")

  const questions = [
    ["title", "Please enter your first update info title here."],
    ["description", "Update info description"]
  ] as const

  // Get info
  const answers: Record<string, string | symbol> = {}
  for (const [key, message] of questions) {
    answers[key] = await text({ message })
  }

  // Confirm cancel
  if (Object.values(answers).some(isCancel)) {
    logWarn("You canceled")
    process.exit(0)
  }

  // Set value
  const {
    title,
    description
  } = answers as Record<string, string>

  const updateData = {
    contents: [
      {
        title: title,
        description: description,
        date: new Date()
      }
    ]
  }

  const policyData = {
    content: "Sample",
    date: new Date()
  }

  // For emulator
  if(isEmulator) {
    await emulatorDb.collection("public").doc("terms").set(policyData)
    await emulatorDb.collection("public").doc("privacy").set(policyData)
    await emulatorDb.collection("public").doc("updates").set(updateData)
  }

  // For product
  await productDb.collection("public").doc("terms").set(policyData)
  await productDb.collection("public").doc("privacy").set(policyData)
  await productDb.collection("public").doc("updates").set(updateData)

  logComplete("Complete to create first firestore data!")
  logWarn("You should set the policy yourself later.")
}

// Main
(async () => {
  // Show logo
  console.log(chalk.blue(figlet.textSync("rt setup", {
    font: "ansi shadow"
  })))

  await startup()
  await selectSetupTypes()

  if (isNormalSetup) {
    await createEnv()

    // Copy scripts/secret.json to functions/src/secret.json
    fs.writeFileSync("./functions/src/secret.json", JSON.stringify(secretFile, null, 2))
  }
  
  await createFirestore()

  // Finish
  logComplete("The setup is now complete!")
  logComplete("Thank you for your hard work!")
  process.exit(0)
})()
